language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn --ignore-optional --frozen-lockfile

# https://github.com/lerna/lerna/issues/2022

after_success:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git remote -v
  - git fetch pub master
  - git branch -r
  - git status
  - git checkout master
  - git status

deploy:
  - provider: script
    script: npx lerna publish --git-remote pub --yes
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
